   try{
window.aax = window.aax|| {};
window.aax.isLoaded = true;
var aaxSettings = {"srvd":"https:\/\/c.aaxads.com","pub":"AAXQJ1RH7","gdpr":"0","gdprconsent":"0","logUrls":{"og":"https:\/\/l3.aaxads.com\/log","aaxdbg":"___stu13p=aveoaamactga5dnnuee25racpo4cuud1vi7rv"}};
var ka="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ta="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ua(){ua=function(){};ta.Symbol||(ta.Symbol=Aa)}var Aa=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function Ba(){ua();var a=ta.Symbol.iterator;a||(a=ta.Symbol.iterator=ta.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&ka(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return Ja(this)}});Ba=function(){}}function Ja(a){var b=0;return Ka(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function Ka(a){Ba();a={next:a};a[ta.Symbol.iterator]=function(){return this};return a}
function La(a,b){Ba();a instanceof String&&(a+="");var c=0,g={next:function(){if(c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g}for(var Na=ta,Oa=["Array","prototype","keys"],Pa=0;Pa<Oa.length-1;Pa++){var Qa=Oa[Pa];Qa in Na||(Na[Qa]={});Na=Na[Qa]}var Ra=Oa[Oa.length-1],Sa=Na[Ra],Ta=Sa?Sa:function(){return La(this,function(a){return a})};
Ta!=Sa&&null!=Ta&&ka(Na,Ra,{configurable:!0,writable:!0,value:Ta});
(function(){function a(a){return"function"===typeof a}function b(b,c,d){a(c)&&(d=c,c=[]);if(void 0===b||""===b||null===b||"[object Array]"!==Object.prototype.toString.call(c)||!a(d))return!1;f[b]=f[b]||{tA:c,callback:d}}function c(b,d){var h=[],e;for(e in b)if(b.hasOwnProperty(e)){var m=b[e];"object"===typeof m||"undefined"===typeof m?h.push(m):(void 0===g[m]&&(g[m]=c(f[m].tA,f[m].callback)),h.push(g[m]))}return a(d)?d.apply(this,h):h}var g={},f={};var d="undefined"!==typeof global&&"object"===typeof module?
global:window;d.__ar=d.__ar||c;d.__ad=d.__ad||b})();
__ad("_",["pqus","uhv",window,document,{}],function(a,b,c,g){function f(a,b,c){b="evt_"+(b||"gbl");X[b]=X[b]||{};X[b][a]=X[b][a]||[];X[b][a].push(c)}function d(a){if(e(a)){var b="evt_"+a;e(X[b])&&!h(X[b])&&ba(X[b],function(a,c){X[b][c]=[]})}}function l(b,c,d,e){e=e||("object"===typeof d?d:{});d="boolean"===typeof d?d:!1;var f="evt_"+(c||"gbl");if(void 0!==X[f]){var g=X[f][b]||[],h={src:c};X.evt_gbl&&X.evt_gbl.gblEvt&&a.X(X.evt_gbl.gblEvt[0],h,e);var k=0;for(c=g.length;k<c;k++)m(g[k])&&a.X(g[k],h,
e);!d&&0<g.length&&(X[f][b]=[])}}function k(a,b){return e(a)?e(b)&&-1!==a.indexOf(b):!1}function h(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0}function e(a){switch(typeof a){case "string":return void 0!==a&&""!==a&&null!==a;case "object":return null!==a;case "number":case "boolean":return!0;default:return!1}}function m(a){return"function"===typeof a}function n(a){return"[object Array]"===Object.prototype.toString.call(a)}function p(a){return e(a)?encodeURIComponent(a):""}function q(a){if(!e(a))return"";
try{return decodeURIComponent(a)}catch(xa){return a}}function r(a){if(!e(a))return{};var b={};var c=a.indexOf("?");if(-1===c)return b;a=a.substring(c+1).split("&");for(c=a.length;c--;){var d=a[c].split("=");b[d[0]]=d[1]}return b}function t(a){this.url=a;this.map=r(this.url)}function u(){var a=!1;try{"object"===typeof c.top&&"object"===typeof c&&(a=c.top!=c)}catch(xa){a=!0}return a}function v(a,b){a=Math.floor(Math.random()*(b-a+1)+a);a>b&&(a=b);return a}function w(a,b,c){c=c||null;b=b||[];return function(){var d=
b.slice(0);0<arguments.length&&Array.prototype.push.apply(d,Array.prototype.slice.call(arguments));return a.apply(c,d)}}function x(a){try{var b=A(a);return[b&&(b.document||b)||!1,b,null]}catch(oa){return[!1,null,"Access Denied"]}}function A(a){try{return a.contentWindow||a.contentDocument}catch(xa){return null}}function z(a){var b;a=a.match(/^([1-9]\d*|0[0-7]*|0x[\da-f]+)(?:\.([1-9]\d*|0[0-7]*|0x[\da-f]+))?(?:\.([1-9]\d*|0[0-7]*|0x[\da-f]+))?(?:\.([1-9]\d*|0[0-7]*|0x[\da-f]+))?$/i);if(!a)return!1;
a[0]=0;for(b=1;5>b;b+=1)a[0]+=!!(a[b]||"").length,a[b]=parseInt(a[b],10)||0;a.push(256,256,256,256);a[4+a[0]]*=Math.pow(256,4-a[0]);return a[1]>=a[5]||a[2]>=a[6]||a[3]>=a[7]||a[4]>=a[8]?!1:a[1]*(1===a[0]||16777216)+a[2]*(2>=a[0]||65536)+a[3]*(3>=a[0]||256)+1*a[4]}function B(){return""+v(0,254)+"."+v(0,254)+"."+v(0,254)+"."+v(0,254)}function E(a,b,c,d,e){c=c||L("@body:0");if(!c)return P("@body:0",100,w(E,[a,b,null,d,e]),!1),null;a=(new y).set("marginWidth",0).set("marginHeight",0).set("scrolling",
"no").set("frameBorder",0).set("height",0).set("width",0).set("id",a).Kl("display:none !important;").done();if(d)for(var f in d)a[f]=d[f];c.firstChild?c.insertBefore(a,c.firstChild):c.appendChild(a);b&&F(a,b);m(e)&&(a.onload=e);return a}function F(b,c){if(b){var d=x(b),e;try{if(null!==d[2])throw d[2];if(e=d[0])e.open(),e.write(c),e.close()}catch(ra){d="javascript:var d=document.open();d.domain='"+g.domain+"';";b.src=d+"void(0);";try{var f=b.contentWindow.document;f.write(c);f.close()}catch(pa){b.src=
d+'d.write("'+c.replace(/"/g,'\\"')+'");d.close();',a.ma(pa)}}}}function N(a,b,c){if(!e(a))return"";e(c)&&e(c.encode)&&!0===c.encode&&(b=p(b));return"&"+a+"="+b}function K(){return/msie|rv:11\.0/.test(Q.toLowerCase())}function J(a){var b=[];ba(a.split("&"),function(a){-1!==a.indexOf("=")&&""!==a&&"action_object_map="!==a.substring(0,18)&&"action_type_map="!==a.substring(0,16)&&"action_ref_map="!==a.substring(0,15)&&"action_action_map="!==a.substring(0,18)&&"fb_"!==a.substring(0,3)&&"fbclid"!==a.substring(0,
6)&&"lcid="!==a.substring(0,5)&&"force_hbtest="!==a.substring(0,13)&&"mnet_test="!==a.substring(0,10)&&"force_hbprv="!==a.substring(0,12)&&"a="!==a.substring(0,2)&&"kwp_0"!==a.substring(0,6)&&"utm_"!==a.substring(0,4)&&"code="!==a.substring(0,5)&&"bcmt"!==a.substring(0,4)&&b.push(a)});return b.join("&")}function H(){if(k(Q,"Trident")||k(Q,"MSIE")){var a=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(Q);if(e(a)&&e(a[1]))return parseFloat(a[1])}return-1}function T(a,b){var d=/interactive|complete|loaded/;
g.attachEvent&&10>=H()&&(d=/complete|loaded/);if(d.test(g.readyState))a();else if(b||ma.T(c,"load",a),!b&&g.addEventListener)ma.T(g,"DOMContentLoaded",a);else if((b=g.documentElement)&&b.doScroll)try{b.doScroll("left"),a()}catch(ja){setTimeout(w(T,[a,!0]),50)}}function y(a){this.frame=a?a.document.createElement("iframe"):g.createElement("iframe")}function L(a){try{var b=a.substr(1).split(":"),c=b[0],d=e(b[1])&&parseInt(b[1],10);switch(a.charAt(0)){case "@":var f=g.getElementsByTagName(c);break;case "#":f=
g.getElementById(c);break;case "$":f=g.getElementsByName(c);break;case ".":f=M(g,c);break;default:f=g.getElementById(a)}return!1===d?f:f[d]}catch(ra){return null}}function P(a,b,c,d){try{var e=L(a),f=ea.uc().fl();e||!d&&f?c.call(null,e||!1):setTimeout(w(P,[a,b,c,d]),b)}catch(pa){setTimeout(w(P,[a,b,c,d]),b)}}function M(a,b,c){if(m(g.getElementsByClassName))return a.getElementsByClassName(b);c=c||"*";b=new RegExp("(^|\\s)"+b+"(\\s|$)");a=a||g;c="*"===c&&a.all?a.all:a.getElementsByTagName(c);a=[];var d=
c.length,e;for(e=0;e<d;e++){var f=c[e];b.test(f.className)&&a.push(f)}return a}function Y(){return e(Q)&&/ip(hone|od|ad)|android|blackberry|kindle|symbian|wap|windows (ce|phone)|palm( os)|iemobile|nokia|mobile/i.test(Q)}function O(){if(k(Q,"Gecko")&&!k(Q,"Trident")&&!k(Q,"MSIE")||k(Q,"webkit"))return!0;if(k(Q,"Trident")||k(Q,"MSIE")){var a=H();if(11<=a)return!0}return!1}function H(){if(k(Q,"Trident")||k(Q,"MSIE")){var a=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(Q);if(e(a)&&e(a[1]))return parseFloat(a[1])}return-1}
function ca(a){var b=a.toString(),c=b.indexOf(".");return-1!==c?parseFloat(b.substr(0,Math.min(c+3,b.length))).toFixed(2):parseFloat(a).toFixed(2)}function Z(a){return e(a)?!isFinite(a)||isNaN(a)?0:a:0}function aa(){return-1!==c.location.href.indexOf("aax_test=")}function da(a,b){if(null===b||"object"!==typeof b||!e(a))return b;ba(b,function(b,c){a[c]=da(a[c],b)});return a}function ba(a,b){if(e(a)){var c=0,d=a.length;if(n(a))for(;c<d;c++)b.call(a[c],a[c],c,d);else for(c in a)a.hasOwnProperty(c)&&
b.call(a[c],a[c],c,0)}}function la(a,b){if(e(a)){m(b)||(b=function(a){return!!a});var c=0,d=a.length;if(n(a))for(;c<d;c++){var f=b.call(a[c],a[c],c);if(e(f))return f}else for(c in a)if(a.hasOwnProperty(c)&&(f=b.call(a[c],a[c],c),e(f)))return f}}function C(a,b){if(!e(a))return[];var c;m(b)||(b=function(a){return!!a});var d=0,f=a.length;if(n(a))for(c=[];d<f;d++)c.push(b.call(a[d],a[d],d));else for(d in c={},a)a.hasOwnProperty(d)&&(c[d]=b.call(a[d],a[d],d));return c}function G(a){return"CSS1Compat"==
a.compatMode?a.documentElement:a.body}function ha(a){var b=a.document,c=void 0,d=void 0;try{var e=G(b);if(!e){b.write('<div id="_mNTemp" style="display:none;"></div>');e=G(a.document);var f=g.getElementById("_mNTemp");f.parentNode.removeChild(f)}e&&(c=e.clientWidth||void 0,d=e.clientHeight||void 0)}catch(pa){}return{width:c,height:d}}function fa(){return!!(c.JSON&&c.JSON.parse&&"function"===typeof JSON.parse&&c.JSON.stringify&&"function"===typeof JSON.stringify)}function R(){return(new Date).getTime()}
function I(a,b,c){c=c||"0";for(a+="";a.length<b;)a+=c;return a}function S(a,b){a=parseInt(a);return!isFinite(a)||isNaN(a)?b:a}function W(){return{Zy:c.pageXOffset||c.scrollX,Jo:c.pageYOffset||c.scrollY}}function U(a){return null===a||"boolean"===typeof a||"number"===typeof a||"string"===typeof a||"symbol"===typeof a||"undefined"===typeof a}function V(a,b,c){V.count=V.count||0;V.threshold=V.threshold||c;setTimeout(function(){a.call(this);e(V.threshold)?(V.count++,V.count<V.threshold&&V(a,b,c)):V(a,
b,c)},b)}function ya(a,b){ba(b,function(b,c){U(b)||n(b)||!a.hasOwnProperty(c)?a[c]=b:a[c]=ya(a[c],b)});return a}function za(a){if(fa())return JSON.stringify(a);if(!e(a)||"object"!==typeof a)return null===a?a+"":a;var b="";ba(a,function(c,d){void 0!==c&&("object"===typeof c&&(c=za(c)),b=n(a)?b+c:b+(d+":"+c),b+=",")});b=b.slice(0,b.length-1);return n(a)?"["+b+"]":"{"+b+"}"}function ia(){try{if("localStorage"in c&&null!==c.localStorage)return c.localStorage.setItem("mntest","mntest"),c.localStorage.removeItem("mntest"),
fa()}catch(na){}return!1}function wa(a,b){var c=0;C(a,function(a){b&&a[b]&&(c+=a[b])});return c}var X={},Q=navigator.userAgent,qa=Math.random(),ma={T:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)},Yh:function(a,b,c){a.removeEventListener?a.removeEventListener(b,c):a.detachEvent&&a.detachEvent("on"+b,c)}};t.prototype.qC=function(){var a=this.map.dn;return a&&q(a)||""};var ea=function(){function b(){function b(){for(d=!0;0<e.length;){var a=e.shift();
a.call(null)}e=[]}function c(){a.X(b)}var e=[];this.Ud=function(a){e.push(a);1!==e.length||d?d&&c():T(c)};this.fl=function(){return d}}var c=null,d=!1;return{uc:function(){null===c&&(c=new b);return c}}}();y.prototype.set=function(a,b){this.frame[a]=b;return this};y.prototype.Kl=function(a){this.frame.style.cssText=a;return this};y.prototype.done=function(){return this.frame};return{ph:function(a){var b=g.cookie.indexOf(a+"="),c=b+a.length+1;if(!b&&a!==g.cookie.substring(0,a.length)||-1===b)return null;
a=g.cookie.indexOf(";",c);-1===a&&(a=g.cookie.length);return unescape(g.cookie.substring(c,a))},im:function(a,b,c,d,e,f,h){var k=new Date;k.setTime(k.getTime());c&&(c*=864E5);h&&(c=6E4*h);h=new Date(k.getTime()+c);g.cookie=a+"="+escape(b)+(c?";expires="+h.toGMTString():"")+(d?";path="+d:"")+(e?";domain="+e:"")+(f?";secure":"")},Ll:I,P:p,Ub:q,zs:function(a){return q(a)!==a},vG:function(a){return k(Q.toLowerCase(),a)},dJ:function(a){var b=a.length;for(a=(a||"0123456789abcdefghijklmnopqrstuvwxyz").split("");b;){var c=
Math.floor(Math.random()*b);--b;var d=a[b];a[b]=a[c];a[c]=d}return a.join("")},wc:function(a,b){return!e(a)&&e(b)?null:(a=(new RegExp("[?&]"+b+"=([^&#]*)","i")).exec(a))?a[1]:null},sc:function(a){a=q(a);return(a=a.match(/^http(?:s)?:\/\/([^/]+)/im))?a[1].toString():""},V:function(){return e(c.location.href)?c.location.href:""},K:function(a){return e(a)},fg:u(),O7:u,ta:v,nr:function(a,b,c){c=Math.pow(10,c||2);return v(a*c,b*c)/c},nC:function(){var a=new Date;a=new Date(Date.UTC(a.getFullYear(),a.getMonth(),
a.getDate()));var b=new Date(Date.UTC(a.getUTCFullYear(),0,1));a.setUTCDate(a.getUTCDate()+4-(a.getUTCDay()||7));return Math.ceil(((a-b)/864E5+1)/7)},Ok:r,ww:t,Tz:function(a){return e(a)?-1!==a.search("^(http(s)?%253A%252F%252F)")?q(a):-1!==a.search("^(http(s)?://)")?p(a):a:""},U:ma,f:m,isArray:n,mi:c.navigator.userAgent.toLowerCase(),LF:O(),ha:function(a,b,c){var d={};e(c)&&e(c.encode)&&(d.encode=c.encode);c="";var f,g=!!b,h=g?b:a,k;for(f in h)if(h.hasOwnProperty(f)){g&&(f=b[f]);if(k=e(a[f]))k=a[f],
k="object"!==typeof k||!1!==k.xG;if(k)if(n(a[f]))for(var l in a[f])c+=N(f+"[]",a[f][l],d);else k="object"===typeof a[f]?a[f].value:a[f],c+=N(f,k,d)}return c},na:N,Q7:function(a){switch(typeof a){case "string":return e(a)&&("1"===a||"true"===a);case "number":return 0!==a;case "boolean":return a;default:return!1}},Ra:function(a,b){return n(a)?la(a,function(a){if(a===b)return!0})||!1:!1},Me:x,wh:A,B:w,bn:y,mc:P,He:M,ls:z,tI:function(a){var b=a.lastIndexOf(".");return-1===b?"":a.substr(0,b+1)+"0"},Hj:k,
ba:L,te:function(a,b){a.firstChild?a.insertBefore(b,a.firstChild):a.appendChild(b)},Lt:function(a){a.parentNode.removeChild(a)},je:F,Z7:function(a,b){F(a,'<!DOCTYPE html><html><head><script type="text/javascript">function makeCall(){var scriptElement = document.createElement(\'script\'), tag = document.getElementsByTagName("script")[0], status = false; scriptElement.type = \'text/javascript\'; scriptElement.async = true; scriptElement.onload = scriptElement.onreadystatechange = function () { if (!status && (!this.readyState || this.readyState === "loaded" || this.readyState === "complete")) { status = true; }};scriptElement.src = "'+
b+'"; tag.parentNode.insertBefore(scriptElement, tag);}\x3c/script></head><body onload="makeCall()"></body></html>')},D8:function(a,b){if(void 0!==a&&void 0!==b&&void 0!==a[b])return a[b]},kd:ea,P7:Y,cG:function(){return e(Q)&&/mac_powerpc|macintosh|mac\\sos|darwin\/|imac\/|macbookpro[\d]/i.test(Q)},ye:E,El:function(b,c,d,f){if(e(b)){"http"!==b.substr(0,4)&&!0===d&&(b=("https:"===g.location.protocol?"https:":"http:")+b);d=g.createElement("script");var h=g.getElementsByTagName("script")[0],k=!1;d.type=
"text/javascript";d.async=!0;f&&f.crossOrigin&&(d.crossOrigin="anonymous");c&&"function"===typeof c&&(d.onload=d.onreadystatechange=function(){k||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(k=!0,a.X(c))});d.src=b;h.parentNode.insertBefore(d,h)}},ml:function(a){if(e(a)){var b=g.createElement("script"),c=g.getElementsByTagName("script")[0];b.type="text/javascript";b.appendChild(g.createTextNode(a));c.parentNode.insertBefore(b,c)}},EG:function(a,b,c){if(e(a)){"http"!==
a.substr(0,4)&&(a=("https:"===g.location.protocol?"https:":"http:")+a);var d="aax_if"+c;f("prvreq",c,b);a=E(d,'<!DOCTYPE html><html><head><script type="text/javascript">function makeCall(){var scriptElement = document.createElement(\'script\'), tag = document.getElementsByTagName("script")[0], status = false; scriptElement.type = \'text/javascript\'; scriptElement.async = true; scriptElement.onload = scriptElement.onreadystatechange = function () { if (!status && (!this.readyState || this.readyState === "loaded" || this.readyState === "complete")) { status = true; window.parent.__ar([\'_\'], function(util){util.triggerEvent(\'prvreq\', "'+
c+'", false, window);});}};scriptElement.src = "'+a+'"; tag.parentNode.insertBefore(scriptElement, tag);}if(("performance" in window) && ("PerformanceObserver" in window)) {var observer = new PerformanceObserver(function (entries) {try {window.parent.aax.processPrefetchPerformanceEntries(entries.getEntries());} catch (e) {}});observer.observe({entryTypes: [\'resource\']});} \x3c/script></head><body onload="makeCall()"></body></html>');return x(a)[1]}},triggerEvent:l,zu:function(a,b,c,d){l("b:"+a,
b,c);l(a,b,c,d);l("a:"+a,b,c)},u:f,J7:function(a,b,c){var d=!1;n(a)&&e(b)&&e(c)&&(ba(a,function(e,f){!0===(new RegExp(b)).test(e)&&(d=!0,a[f]=c)}),!1===d&&a.push(c))},da:ca,xe:function(){aa()&&c.console&&c.console.log(Array.prototype.slice.call(arguments))},Ns:aa,qr:B,y6:function(a,b,c){var d=[],f,g=[],h={};if(0===a.length)return[""];e(c)&&e(c.encode)&&(h.encode=c.encode);for(m in a[0])a[0].hasOwnProperty(m)&&d.push(m);var k="",l=K();var m=0;for(c=a.length;m<c;m++){var n="";var p=0;for(f=d.length;p<
f;p++)n+=N(d[p]+"[]",a[m][d[p]],h);l&&e(b)?n.length>b?g.push(n):(k+n).length>b?(g.push(k),k=n):k+=n:k+=n}g.push(k);return g},dh:function(a,b){var c="",d={};e(b)&&e(b.encode)&&(d.encode=b.encode);ba(a,function(a,b){c+=N(b,a,d)});return c},o:function(a,b){a.V8=b;for(var c in b.prototype)a.prototype[c]=b.prototype[c];a.prototype.constructor=a},Ph:function(a,b){b*=6E4;return R()-a>b?!1:!0},F:new function(){var a={},b,c=!1;this.startTime=function(){return b};this.start=function(){b=(new Date).getTime();
c=!0};this.stop=function(){(new Date).getTime();c=!1};this.pc=function(){return(new Date).getTime()-b};this.fa=function(b){a[b]={};a[b].startTime=c?this.pc():-1};this.pa=function(b){a.hasOwnProperty(b)&&(a[b].endTime=-1===a[b].startTime?-1:this.pc())};this.time=function(b){return a.hasOwnProperty(b)?(a[b].endTime||this.pa(b),a[b].endTime-a[b].startTime):-1};this.getTime=function(b){return a.hasOwnProperty(b)?this.pc()-a[b].startTime:-1}},extend:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=
b[c]);return a},Tl:da,dc:function(){try{return/loaded|complete/.test(g.readyState)}catch(na){return!1}},V6:function(a,b){b="evt_"+(b||"gbl");X[b]&&X[b][a]&&0<X[b][a].length&&(X[b][a]=[])},w8:function(){for(var a in X)X.hasOwnProperty(a)&&-1!==a.indexOf("evt_")&&-1===a.indexOf("cmd")&&(X[a]={})},x8:d,y8:function(){d("gbl")},a:e,IF:function(a){return"undefined"!==typeof a},trim:function(a){return e(a)?a.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,""):""},I:h,Dl:function(a){return"object"===typeof a&&
null!==a&&!h(a)},hp:function(a){if(!n(a))return{};for(var b=0,c=a.length,d={};b<c;b++)d[a[b]]=b+1;return d},map:C,reduce:function(a,b,c){if(m(b)){if(n(a)){var d=0;var e=a.length;if("undefined"===typeof c){for(;d<e&&!(d in a);)d++;if(d>=e)return;c=a[d++]}for(;d<e;d++)d in a&&(c=b(c,a[d],d,a));return c}c=c||"";for(d in a)a.hasOwnProperty(d)&&(c=b(c,a[d],d,a));return c}},filter:function(a,b){if(!e(a))return[];var c;m(b)||(b=function(a){return!!a});var d=0,f=a.length;if(n(a))for(c=[];d<f;d++)b.call(a[d],
a[d],d)&&c.push(a[d]);else for(d in c={},a)a.hasOwnProperty(d)&&b.call(a[d],a[d],d)&&(c[d]=a[d]);return c},Ip:function(a,b){b=b.split(".");var c;for(c=0;c<b.length;++c){if(void 0===a[b[c]])return;a=a[b[c]]}return a},D:la,some:function(a,b){if(!e(a))return!1;m(b)||(b=function(a){return!!a});var c=0,d=a.length;if(n(a))for(;c<d;c++){var f=b.call(a[c],a[c],c);if(!0===f)return f}else for(c in a)if(a.hasOwnProperty(c)&&(f=b.call(a[c],a[c],c),!0===f))return f;return!1},c:ba,$p:K,Md:ha,xq:function(){return ha(c).width},
wq:function(){return ha(c).height},sE:function(){try{return c.screen.width+"x"+c.screen.height}catch(na){return""}},Pd:fa,ia:R,rg:function(a,b){b=Math.pow(10,b);return Math.round(a*b)/b},tu:function(a){return(a||"").replace(/\/$/,"")},zh:function(a){if(m(Object.keys))return Object.keys(a);var b=[];ba(a,function(a,c){b.push(c)});return b},nD:function(a){if(n(a)&&(a=Math.max.apply(null,a),!isNaN(a)))return a},d8:function(a,b){if("object"!==typeof a||"string"!==typeof b)return!1;if("string"===typeof a.className)return(new RegExp("(^|\\s)"+
b+"(\\s|$)")).test(a.className)},ge:function(a,b,c){var d=m(c)?c:Date.now,e=d();return function(){var c=d();c-e>=a&&(e=c,b.apply(null,arguments))}},Ca:function(a,b){return a.style[b]?a.style[b]:a.currentStyle?a.currentStyle[b]:g.defaultView&&g.defaultView.getComputedStyle?(b=b.replace(/([A-Z])/g,"-$1"),b=b.toLowerCase(),(a=g.defaultView.getComputedStyle(a,""))&&a.getPropertyValue(b)):null},Cp:function(d,f,g,h){function k(){(g.onerror||m)()}function l(){(g.onload||m)(n.response||n.responseText)}function m(){}
if(!c.XMLHttpRequest)return(g.Up||m)(),null;var n=new XMLHttpRequest,p=!1;d=(d||b.Jv.C_).toUpperCase();if("withCredentials"in n)n.open(d,f,!0),n.withCredentials=e(g.withCredentials)?g.withCredentials:!0;else if(c.XDomainRequest){n=new XDomainRequest;try{n.open(d,f)}catch(sa){return(g.Up||m)(),null}}else return(g.Up||m)(),null;n.onload=n.onreadystatechange=function(){p||4!=n.readyState||(200==n.status?a.X(l):k(),p=!0)};n.onerror=k;n.onabort=k;n.send(h);return!0},Oq:H,Qk:function(a){var b;try{a&&a.data&&
"string"===typeof a.data&&fa()&&(b=JSON.parse(a.data))}catch(oa){}return b},Vs:function(){return m(c.navigator.sendBeacon)?!0:!1},EF:function(){return"withCredentials"in new XMLHttpRequest||"undefined"!=typeof XDomainRequest?!0:!1},XC:function(a){function b(a){a=a.match(/\d+/g);return null===a||0===a.length?"":a[0]}a=a.frameElement;var c=String(a.height||"0"),d=String(a.width||"0");-1!==c.indexOf("%")||-1!==d.indexOf("%")?(d=a.getBoundingClientRect&&a.getBoundingClientRect()||{},c=Math.ceil(d.height||
a.clientHeight)||0,d=Math.ceil(d.width||a.clientWidth)||0):(c=b(c),d=b(d));return d+"x"+c},KE:function(){try{var a=c.localStorage}catch(xa){}return e(a)&&(a=a.getItem("tpck"),e(a))?a:!1===(c&&c.navigator&&c.navigator.cookieEnabled||navigator&&navigator.cookieEnabled)?0:""},Dq:function(a){a=L("#"+a);var b={},c=W().Zy,d=W().Jo,f={};e(a)&&m(a.getBoundingClientRect)&&(f=a.getBoundingClientRect());b.Y8=S(f.top,0);b.w6=S(f.bottom,0);b.X7=S(f.left,0);b.z8=S(f.right,0);b.top=S(f.top+d,0);b.bottom=S(f.bottom+
d,0);b.left=S(f.left+c,0);b.right=S(f.right+c,0);b.offsetX=S(c,0);b.offsetY=S(d,0);return b},mb:function(){var a=Array.prototype.slice.call(arguments),b=a[0];a.shift();ba(a,function(a){n(a)?Array.prototype.push.apply(b,a):b.push(a)});return b},Ga:S,Request:function(a){var b={};this.input=function(a,c){b[a]=c;return this};this.get=function(a){return e(b[a])?b[a]:""};this.ft=function(a){a&&(b=a);return this};this.freeze=function(){return b};this.deleteProperty=function(a){delete b[a]};a&&(b=a)},up:function(a){if(!e(a))return"";
var b=a.split("?")[0].split("#")[0];if(!e(b))return"";b=b.replace(/\/$/,"");var c=a.indexOf("#"),d="";0<c&&(d=a.substring(c+1));var f=a.indexOf("?");c=0<c?c:a.length;var g="";0<f&&(g=a.substring(f+1,c));a=J(g);e(a)&&(b=b+"?"+a);d=J(d);e(d)&&(b=b+"#"+d);return b},eH:function(a,b){try{return O()?(a.document.write(b),a.document.close()):(a.hbContent="<!DOCTYPE html><html><head></head><body>"+b+"</body></html>",a.location.replace('javascript:window["hbContent"];')),!0}catch(oa){return!1}},Ef:function(a,
b,c){return(new y).set("marginWidth",0).set("marginHeight",0).set("scrolling","no").set("frameBorder",0).set("height",c||0).set("width",b||0).set("id",a).set("allowtransparency","true").done()},xl:U,qz:function(a,b){e(b)||(b=0);return new Date(a.getTime()+6E4*b)},iH:V,M:function(b,c){return"function"===typeof b?w(a.X,[c||null,b]):b},Ah:function(){try{var a=c.document.body,b=c.document.documentElement;return Math.max(a.scrollHeight,a.offsetHeight,b.clientHeight,b.scrollHeight,b.offsetHeight)}catch(oa){return 0}},
T7:function(){return!1},jb:function(){return I(z(B()),10)+""+v(1E6,9999999)+""+(new Date).getTime().toString()},Za:function(a,b){return a*(1+b/100)},St:Z,getFloatValue:function(a){a=Z(a);a=ca(a);return parseFloat(a)},Bt:ya,Nb:function(a){return e(a)&&(1>a||1<a*qa)},Zf:function(){return("https:"===c.location.protocol?"https:":"http:")+"//"+c.location.hostname},TG:za,Gj:function(a){return"http"!==a.substr(0,4)?("https:"===g.location.protocol?"https:":"http:")+a+a:a},AJ:function(a,b){return a.length>
b?a.substr(0,b):a},zD:W,ME:function(a){for(var b=a.parent;b!==c.top;)a=a.parent,b=b.parent;return a},i7:function(a){(new Image).src=a},postMessage:function(a,b,d){var f=A(d);b&&e(f)&&(c.postMessage&&m(f.postMessage)?f.postMessage(a,"*"):b&&("object"===typeof a&&(a=za(a),a=escape(a)),b=b+"#"+g.location.href,d.src=b,f.location=b.replace(/#.*$/,"")+"#_CPM$"+a))},OF:function(){return!!c.EventSource},fe:ia,Gh:function(){return Y()&&!ia()},SD:function(a,b){if(b){var c=wa(a,b),d=v(0,100),e=0,f=null;return 1>
c||100<c?f:f=la(a,function(a){if(a[b]&&(e+=a[b],d<e))return a})}}}});
__ad("pqus",[window,document,{}],function(a,b){function c(){var d,e=0;for(d=0;3>d;d++)e+=n[d].length;if(0!==e){var f=new Image,g=("https:"===b.location.protocol?"https":"http")+"://l3.aaxads.com/nerrping.php",u="",v=0;for(d=2;0<=d;d--){for(e=n[d].length;0<e;){var w=1===d?n[d][0]:{logLevel:n[d][0].logLevel,errorVal:{name:n[d][0].errorVal.name,type:k,svr:h,message:n[d][0].errorVal.message,line:n[d][0].errorVal.lineNumber,description:n[d][0].errorVal.description,stack:n[d][0].errorVal.stack}};w="object"===
typeof JSON&&"function"===typeof JSON.stringify?JSON.stringify(w):void 0;if(1200>=w.length+u.length||!u.length)0!==u.length&&(u+=","),u+=w,n[d].shift(),e--;else{v=1;break}}if(v)break}u=encodeURIComponent("["+u+"]");d=g+"?d="+u+"&userAgent="+m+"&requrl="+encodeURIComponent(a.location.href)+"&img=logo.gif";f.src=d}l(c,2500)}function g(a){"undefined"===typeof a.logLevel&&(a={logLevel:3,errorVal:a});3<=a.logLevel&&n[a.logLevel-1].push(a)}function f(a,b,c){this.name=a;this.message=b;this.logLevel=c}function d(){var a=
Array.prototype.slice.call(arguments),b=a.length,c=null,d=null;if("object"===typeof a[b-1]&&a[b-1].constructor===f){var e=a[b-1];b--}if("function"===typeof a[0]){var h=a.shift();b--}else c=a.shift(),h=a.shift(),b-=2;a=a.slice(0,b);try{return h.apply(c,a)}catch(w){return e&&(w.name=e.name+" ("+w.name+")",w.message=e.message+" ("+w.message+")",d=e.logLevel),g({logLevel:d||3,errorVal:w}),new f}}function l(b,c){if("function"===typeof b)return a.setTimeout(function(){d(b)},c)}var k="",h="",e,m=encodeURIComponent(navigator.userAgent),
n=[];for(e=0;3>e;e++)n[e]=[];a.addEventListener("load",c);return{X:d,ma:g,zg:function(a){k=a},Yt:function(a){h=a},hu:function(){},setTimeout:l}});
__ad("qlf",["pqus",window,"_","uhv","performanceobserver"],function(a,b,c,g,f){function d(a){var b=c.extend({},m);return a=c.extend(b,a)}function l(b,d,e){!0===d.Zp&&(b=c.Gj(b));d=document.createElement("script");var f=document.getElementsByTagName("script")[0],g=!1;d.type="text/javascript";d.async=!0;e&&"function"===typeof e&&(d.onload=d.onreadystatechange=function(){g||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(g=!0,a.X(e))},d.onerror=function(){e.call(null,"error")});
d.src=b;f.parentNode.insertBefore(d,f)}function k(a,b){var d=new Image;a=c.AJ(a,8E3);d.onload=b;d.src=a;d.onerror=function(){b.call(null,"error")}}function h(a,b){var d=new XMLHttpRequest,e="POST"===b.method?a.url:a;if(!("withCredentials"in d))return d=new XDomainRequest,d.open(b.method,a),d;d.open(b.method,e,!0);d.withCredentials=c.a(b.withCredentials)?b.withCredentials:!0;return d}function e(a,b,c){var d=!1,e=a.Ol;try{var f=h(a,b)}catch(v){c.call(null,500,"error")}f.onload=f.onreadystatechange=
function(){if(!d&&4===this.readyState)return d=!0,200===this.status?c.call(null,null,this.response||this.responseText):c.call(null,this.state,"error")};f.send(e)}var m={Y:["plvf"],method:"GET",type:"img",Zp:!1};return{submit:function(a,g,h){c.isArray(a)||(a=[a]);g=d(g);h=h||function(){};c.c(a,function(a){var d=f.B(a,g,h);switch(g.type){case "img":k(a,d);break;case "script":l(a,g,d);break;case "xhr":e(a,g,d);break;case "sb":d=g;c.Vs()&&(a=!1===b.navigator.sendBeacon(a.url,a.Ol)?"error":"success",f.bp(d,
a));break;case "ifScr":var m=g,n="aax_if"+m.name;a=c.Gj(a);c.u("prvreq",m.name,d);a=c.ye(n,'<!DOCTYPE html><html><head><script type="text/javascript">function makeCall(){var scriptElement = document.createElement(\'script\'), tag = document.getElementsByTagName("script")[0], status = false; scriptElement.type = \'text/javascript\'; scriptElement.async = true; scriptElement.onload = scriptElement.onreadystatechange = function () { if (!status && (!this.readyState || this.readyState === "loaded" || this.readyState === "complete")) { status = true; window.parent.__ar([\'_\'], function(util){util.triggerEvent(\'prvreq\', "'+
m.name+'", false, window);});}};scriptElement.src = "'+a+'"; tag.parentNode.insertBefore(scriptElement, tag);}if(("performance" in window) && ("PerformanceObserver" in window)) {var observer = new PerformanceObserver(function (entries) {try {window.parent.aax.processPrefetchPerformanceEntries(entries.getEntries());} catch (e) {}});observer.observe({entryTypes: [\'resource\']});} \x3c/script></head><body onload="makeCall()"></body></html>');c.Me(a)}})},stream:function(a,c,e){e=e||function(){};c=d(c);
var g=f.B(a,c,e);try{var h=new b.EventSource(a,{withCredentials:!0})}catch(u){g.call(null,"error")}"undefined"!==typeof h&&(h.onopen=g,h.onerror=function(){g.call(null,"error")});return h}}});
__ad("performanceobserver",function(){return{B:function(a,b,c){return c},bp:function(){}}});
__ad("postmessagemanager","_ qlf srvwpf pqus ef ie postdata inmemdatasource uhv".split(" "),function(a,b,c,g,f,d,l,k){function h(b,c){a.c(c,function(a,c){b.setTargeting(c,a)})}function e(b){a.c(b,function(a,b){window.googletag.pubads().setTargeting(b,a)})}function m(b,c,d,f,g){window.googletag.cmd.push(function(){v=window.googletag.defineSlot(b,f,"aax_standard").addService(window.googletag.pubads());window.googletag.pubads().set("page_url",k.get("referer"));window.googletag.pubads().set("adsense_ad_types",
"text");k.get("gdpr")&&window.googletag.pubads().setRequestNonPersonalizedAds(1);window.googletag.enableServices();w.enqueue("aax_standard",g);h(v,c);e(d);a.mc("#aax_standard",100,function(){window.googletag.display("aax_standard")},!0)})}function n(c){var d=k.for(c).get("isAAX"),e=k.for(c).get("dfpData");if(a.a(e)){var h=(new l).set("dfpadvid",e.advertiserId).set("dfpcmpid",e.campaignId).set("crtid",e.creativeId).set("liid",e.lineItemId).set("lbid",e.labelIds).set("isbckfl",e.isBackfill).set("isEmp",
e.isEmpty).set("sz",e.dfpDivSize).set("srcAgnCrid",e.sourceAgnosticCreativeId).set("srcAgnLid",e.sourceAgnosticLineItemId).set("srvcnm",e.serviceName).set("auPt",k.get("auPt")).set("aId",c).set("isAaxWon",d).set("type","renderad");d||h.set("adc",e.adcode);h.target(k.get("tarOg"));h.Xb(k.get("fid"));window.top.postMessage(h.W(),h.target());d=k.for(c).get("status")||!1;c=k.for(c).get("lpx");d&&b.submit(c,{type:"img",Y:["win","plvf"]})}}function p(a){var b=a.get("ac"),c=a.get("lpx"),d=a.get("tarM"),
e=a.get("aId");k.set("aid",e);k.for(e).set("adCode",b).set("lpx",c).set("isAAX",!1);window.googletag.cmd.push(function(){v.clearTargeting();w.enqueue("aax_standard",e);h(v,d);window.googletag.pubads().refresh([v])})}function q(a,b){var c=(new l).ub(b.data);switch(c.get("type")){case "refReq":p(c);break;case "initRen":a=c.get("aId");b=c.get("ac");var d=c.get("lpx"),e=c.get("tarM"),h=c.get("gtm"),f=c.get("szs");c=c.get("auPt");k.set("aid",a);k.set("auPt",c);k.for(a).set("isAAX",!1).set("lpx",d).set("adCode",
b);m(c,e,h,f,a)}}function r(){d.ds()}function t(b){var c=b.slot,d=c.getTargetingMap()||{},e=c.getResponseInformation()||{},h=w.gh("aax_standard");d.slotElementId=c.getSlotElementId();d.advertiserId=e.advertiserId||"";d.campaignId=e.campaignId||"";d.creativeId=e.creativeId||"";d.labelIds=e.labelIds||[];d.lineItemId=e.lineItemId||"";d.isBackfill=e.isBackfill?"1":"0";d.dfpDivSize=a.isArray(b.size)?b.size.join("x"):"";d.serviceName=b.serviceName||"";d.isEmpty=b.isEmpty?"1":"0";d.sourceAgnosticCreativeId=
b.sourceAgnosticCreativeId||"";d.sourceAgnosticLineItemId=b.sourceAgnosticLineItemId||"";b=a.ba("#aax_standard");if(a.a(b)){b:{b=b.getElementsByTagName("iframe")[0];try{if(!a.a(b)&&!a.a(b.contentDocument)){var f=null;break b}var g=b.contentDocument;f=a.a(g)&&0!==g.getElementsByTagName("html").length?g.getElementsByTagName("html")[0]:null;break b}catch(K){}f=void 0}f=a.a(f)?f.innerHTML:""}else f="";d.adcode=f;k.for(h).set("dfpData",d);(d=k.for(h).get("isAAX"))||(d=k.for(h).get("dfpData"),d=a.a(d)&&
a.a(d.adcode)?-1!==d.adcode.indexOf("aax.deliverExchangeDemand"):!1);d?(k.for(h).set("isAAX",!0),n(h)):(d=250,a.a(k.get("pmdelay"))&&(d=k.get("pmdelay")),window.setTimeout(a.M(a.B(n,[h])),d))}function u(){function b(){window.googletag.pubads().addEventListener("slotRenderEnded",a.M(t));window.googletag.pubads().addEventListener("slotOnload",a.M(r))}window.googletag&&window.googletag.cmd||(window.googletag=window.googletag||{},window.googletag.cmd=window.googletag.cmd||[]);a.isArray(window.googletag.cmd)?
window.googletag.cmd.unshift(b):window.googletag.cmd.push(b)}var v,w=new function(){var b={};this.enqueue=function(a,c){b[a]=b[a]||[];b[a].push(c)};this.gh=function(c){if(a.a(c)&&(c=b[c],a.a(c)&&a.isArray(c)&&0<c.length))return c.shift()}};return{A:function(){a.u("aaxOnMes","gbl",a.M(q));u()}}});
__ad("srvwpf",function(){return{C:{},od:{},me:{}}});
__ad("ef",function(){return{Hi:{},qf:{},Hg:{},C:{},aj:{},bj:{},pe:{},nd:{},od:{}}});
__ad("of",function(){return{cj:{},on:{},Vn:{},by:{},co:{},Xu:{},eb:{},qf:{},Si:{},Rv:{},Vy:{},Sg:{},Mx:{},me:{},Ti:{},pe:{}}});
__ad("postdataconstants",function(){return{C:{}}});
__ad("uhv",function(){return{Event:{},Iv:{},dw:{},px:{},Sy:{},rv:{},Hv:{},Ri:{},me:{},Py:{}}});
__ad("wf",function(){return{Ei:{},Ng:{}}});
__ad("aaxframelogmanager",[window.aaxSettings,"_","of","uhv","inmemdatasource"],function(a,b,c,g,f){return{o6:function(c){var d={};d.hyw=c;d.flg=a.pub;d.jgsu=f.get("gdpr")?"1":"0";c=a.logUrls&&a.logUrls.og;var g=a.logUrls&&a.logUrls.aaxdbg;(new Image).src=c+"?"+g+b.ha(d)}}});
__ad("inmemdatasource",["_","uhv"],function(a){function b(){var b={};this.set=function(c,d){a.a(c)&&a.xl(c)&&(b[c]=d);return this};this.get=function(a){return b[a]||""}}function c(c){if(!a.a(c)||!a.xl(c))return null;c=c.toString();a.a(g[c])||(g[c]=new b);return g[c]}var g={},f={};return{set:function(a,b){return c("primary_in_mem_resource").set(a,b)},get:function(a){return c("primary_in_mem_resource").get(a)},OI:function(a,b){f[a]=b},eg:function(a){f[a]||(f[a]=[]);return f[a]},for:c}});
__ad("ie","feedbackuimanager _ srvwpf postdata uhv inmemdatasource".split(" "),function(a,b,c,g,f,d){function l(a){a=(new g).set("type","feedback").set("aId",d.get("aid")).set("rate",a.Zc).set("dist",a.reason&&a.reason.distracting).set("ntRel",a.reason&&a.reason.notrelevant).set("prLb",a.reason&&a.reason.poorlylabeled).set("misL",a.reason&&a.reason.misleading).set("toob",a.reason&&a.reason.toobig);a.target(d.get("tarOg"));a.Xb(d.get("fid"));window.top.postMessage(a.W(),a.target())}function k(){function b(){l(e.lq())}
var c={hk:3,du:!0,oc:{right:"0px",bottom:"0px"},kt:h,Hl:"v1"};e=a(c);e.sJ(function(a){a>c.hk&&l(e.lq())});e.rJ(b);e.qJ(b);e.A()}var h,e,m=!1;return{ds:function(){if(m)e.IH();else{var a=document.createElement("div");for(a.innerHTML='<span class="advertisement-on-ad">AD</span><div id="aax-feedback" class="container aax-popup hide"> <div class="popup-container"> <div class="logo-wrapper"> </div><div class="rating-block-wrapper"> <div class="aax-rating-block"> <div class="aax-rating hide"> <div class="aax-rating-text-wrapper"> <p class="aax-rating-text">We use user feedback to show better ads</p></div><div class="aax-stars-wrapper"> <p>Rate this Ad</p><ul class="star-list"> <li data-rate="5"></li><li data-rate="4"></li><li data-rate="3"></li><li data-rate="2"></li><li data-rate="1"></li></ul> </div></div><div class="aax-rating-feedback hide"> <ul class=""> <li> <label for="distracting"> <input type="checkbox" name="distracting" value="distracting" id="distracting"> <span class="checkmark"></span> Distracting </label> </li><li> <label for="poorlylabeled"> <input type="checkbox" name="poorlylabeled" value="poorlylabeled" id="poorlylabeled"> <span class="checkmark"></span> Poorly Labeled </label> </li></ul> <ul class=""> <li> <label for="toobig"> <input type="checkbox" name="toobig" value="toobig" id="toobig"> <span class="checkmark"></span> Too Big </label> </li><li> <label for="notrelevant"> <input type="checkbox" name="notrelevant" value="notrelevant" id="notrelevant"> <span class="checkmark"></span> Not Relevant </label> </li></ul> <ul class="last-column"> <li> <label for="misleading"> <input type="checkbox" name="misleading" value="misleading" id="misleading"> <span class="checkmark"></span> Misleading Ad </label> </li></ul> <span class="submit"> <button type="button" name="button">Submit</button> </span> </div><div class="aax-rating aax-rating-last hide"> <p> <i></i> <span>Thanks for submitting the feedback</span> </p></div></div></div><p class="aax-optout hide"> Cookies help us deliver our services better. Click here to <a href="http://optout.aaxads.com" target="_blank">Opt Out</a>. </p></div><span class="close-feedback"> <i></i> </span></div><span class="feedback-cta"> <i></i> </span>';a.firstChild;)document.body.appendChild(a.firstChild);
k();m=!0}},oz:function(){h=window.aaxSettings&&window.aaxSettings.srvd;var a=document.createElement("link");a.rel="stylesheet";a.type="text/css";a.href=h+"/aax-style.css";document.getElementsByTagName("head")[0].appendChild(a)}}});
__ad("feedbackuimanager",function(){return function(a){function b(){for(var b=document.querySelectorAll(a.Sa+" .star-list li"),c=0;c<b.length;c++)p.ah(b[c],"click",q.HI);p.ah(document.querySelector(a.Sa+" .aax-rating-feedback .submit button"),"click",q.kI);p.ah(document.querySelector(a.Ff),"click",q.qu);p.ah(document.querySelector(a.Sa+" .close-feedback"),"click",function(){q.$H();q.Ur()})}function c(b,c){var d=document.querySelector(a.Sa+" .logo-wrapper"),e=document.createElement("IMG");e.src=a.kt+
"/"+c+(null===a.Hl?"":"?ver="+a.Hl);e.alt="AAX";e.className="portrait"===b?"logo logo-portrait":"logo logo-standard";d.appendChild(e)}a=a?a:{};var g={top:"auto",right:"auto",bottom:"auto",left:"auto"},f={Sa:"#aax-feedback",hk:3,Ff:".feedback-cta",Im:null,Hm:null,du:!1,oc:null,kt:"images",Hl:null},d={},l={Zc:null,reason:{}},k=[],h=[],e=[],m={},n=!1,p={f:function(a){return"[object Function]"==={}.toString.call(a)},ah:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+
b,c)},YE:function(a,b){return-1<a.className.indexOf(b)},qd:function(a,b){if(!p.YE(a,b)){var c=a.className.split(" ");c.push(b);a.className=c.join(" ")}return a},zc:function(a,b){a.className=a.className.replace(b,"").replace(/\s{2,}/g," ").replace(/^\s\s*/,"").replace(/\s\s*$/,"");return a},pk:function(a){var b=[];a=document.querySelectorAll(a+" input");for(var c=0;c<a.length;c++)a[c].checked&&b.push(a[c]);return b},uI:function(){var b="",d=document.querySelector(a.Sa),e=window,h=document,f=h.documentElement,
g=h.getElementsByTagName("body")[0];h=e.innerWidth||f.clientWidth||g.clientWidth;e=e.innerHeight||f.clientHeight||g.clientHeight;p.zc(d,"portrait");p.zc(d,"landscape");p.zc(d,"standard");h<e?b="portrait":675<=h?b="landscape":225<=h&&(b="standard");"portrait"===b&&360>e?b="basic-small portrait":"landscape"===b&&90>e?b="basic-small horizontal":"standard"===b&&220>e&&(b="basic-small horizontal");-1<b.indexOf("portrait")?c("portrait","logo-vertical.png"):c("landscape","logo.png");p.qd(d,b)},cI:function(){for(var b in g)g.hasOwnProperty(b)&&
(a.oc.hasOwnProperty(b)||(a.oc[b]=g[b]))},bI:function(){var b=document.querySelector(a.Ff);b.style.top=a.oc.top;b.style.right=a.oc.right;b.style.bottom=a.oc.bottom;b.style.left=a.oc.left}},q={HI:function(b){l.Zc=(b.target||b.srcElement).getAttribute("data-rate");for(b=0;b<k.length;b++)k[b].call(m,l.Zc);l.Zc<=a.hk?q.show(".aax-rating-feedback"):q.show(".aax-rating-last")},kI:function(){for(var b=p.pk(a.Sa+" .aax-rating-feedback"),c=0;c<b.length;c++)l.reason[b[c].value]=1,b[c].checked=!1;for(b=0;b<
h.length;b++)h[b].call(m,l.Zc,l.reason);q.show(".aax-rating-last")},$H:function(){if(!n&&null!==l.Zc){for(var b=p.pk(a.Sa+" .aax-rating-feedback"),c=0;c<b.length;c++)l.reason[b[c].value]=1,b[c].checked=!1;for(b=0;b<e.length;b++)e[b].call(m,l.Zc,l.reason)}},show:function(b){n=".aax-rating-last"===b;for(var c=document.querySelector(a.Sa+" "+b),d=document.querySelector(".aax-popup"),e=document.querySelectorAll(".show"),h=0;h<e.length;h++)e[h]!==d&&(p.zc(e[h],"show"),p.qd(e[h],"hide"));-1<c.className.indexOf("hide")&&
p.zc(c,"hide");p.qd(c,"show");c=document.querySelector(a.Sa+" .aax-optout");".aax-rating"===b?(p.zc(c,"hide"),p.qd(c,"show")):(p.zc(c,"show"),p.qd(c,"hide"))},qu:function(){var b=document.querySelector(a.Sa+".aax-popup");-1<b.className.indexOf("hide")&&p.zc(b,"hide");p.qd(b,"show");n||q.Ot()},Ur:function(){var b=document.querySelector(a.Sa+".aax-popup");-1<b.className.indexOf("show")&&p.zc(b,"show");p.qd(b,"hide")},Ot:function(){q.show(".aax-rating");for(var b=p.pk(a.Sa+" .aax-rating-feedback"),c=
0;c<b.length;c++)b[c].checked=!1;l.Zc=null;l.reason={}}};m.A=function(){a.oc&&p.cI();for(var c in f)f.hasOwnProperty(c)&&"undefined"===typeof a[c]&&(a[c]=f[c]);for(var e in a)a.hasOwnProperty(e)&&(d[e]=a[e]);a.oc&&p.bI();a.du&&p.uI();if(null===document.querySelector(a.Sa))throw"Container selector "+a.Sa+" is not found/invalid";if(null===document.querySelector(a.Ff))throw"CTA selector "+a.Ff+" is not found/invalid";if(a.Hm||0===a.Hm)document.querySelector(a.Sa).style.zIndex=a.Hm;if(a.Im||0===a.Im)document.querySelector(a.Ff).style.zIndex=
a.Im;b();return m};m.lq=function(){return l};m.sJ=function(a){p.f(a)&&k.push(a)};m.rJ=function(a){p.f(a)&&h.push(a)};m.qJ=function(a){p.f(a)&&e.push(a)};m.config=d;m.IH=q.Ot;m.l8={show:q.qu,Tr:q.Ur};return m}});
__ad("postdata",["_","postdataconstants"],function(a,b){function c(){var b={},c=this;this.get=function(a){return b[a]};this.set=function(a,c){b[a]=c;return this};this.W=function(){return a.extend({},b)};this.ub=function(c){b=a.extend({},c);return this};this.id=function(b){a.a(b)&&c.set("pid",b);return c.get("pid")};this.Xb=function(b){a.a(b)&&c.set("pfid",b);return c.get("pfid")};this.target=function(b){a.a(b)&&c.set("ptarget",b);return c.get("ptarget")};this.source=function(b){if(a.a(b))c.set("psource",
b);else return c.get("psource")};c.set("pid",g++)}var g=1;c.C=b.C;return c});
__ad("ddagif","_ pqus inmemdatasource postmessagemanager postdata uhv qlf".split(" "),function(a,b,c,g,f,d,l){function k(a,d,f){d=!1;c.for(f).set("isAAX",!0);var e=c.for(f).get("adCode");try{a.document.open(),a.document.write(e),a.document.close(),d=!0}catch(p){b.ma("Error while rendering the adcode"),d=!1}c.for(f).set("status",d)}return{A:function(){a.a(window.aaxSettings.pmdelay)&&c.set("pmdelay",window.aaxSettings.pmdelay);g.A();l.submit("//www.googletagservices.com/tag/js/gpt.js",{Y:["scr","plvf"],
type:"script"});window.aax.deliverExchangeDemand=k}}});
__ad("displayframecore","_ pqus uhv postdata ie inmemdatasource srvwpf ddagif".split(" "),function(a,b,c,g,f,d,l,k){function h(){var a=(new g).set("phs",!0);a.target(d.get("tarOg"));a.Xb(d.get("fid"));window.top.postMessage(a.W(),a.target())}function e(b){var c=window.document.createElement("div");c.id="aax_standard";a.mc("@body:0",100,function(d){d.appendChild(c);a.f(b)&&b()})}b.zg("AAX");window.aax=window.aax||{};(function(){var c=window.aax.__conf;try{if(a.a(window.name)){var e=JSON.parse(window.name);
a.extend(c,e)}}catch(p){b.ma("Failed to read window name")}a.c(c,function(a,b){d.set(b,a)})})();d.set("gdpr","1"===window.aaxSettings.gdpr);d.set("gdprconsent",window.aaxSettings.gdprconsent);a.U.T(window,"message",a.M(function(b){b.data&&b.origin===b.data.src&&b.data.id===a.Ga(d.get("fid"))&&("initRen"===b.data.type||"refReq"===b.data.type)&&a.triggerEvent("aaxOnMes","gbl",!0,b)}));return{start:function(){e(h);k.A();f.oz()}}});window.__ar(["displayframecore"],function(a){a.start()});
} catch (err) {
    window.aax.err = err;
    window.aax.errConsts = {"name":"aaxDisplayIframe","type":"AAX_DISPLAY_IFRAME","svr":"2019102110_699","servname":"c8-web-9","message":"aaxDisplayIframe encountered an error","path":"\/nerrping.php","customerId":"AAXQJ1RH7","hostName":"https:\/\/l3.aaxads.com","get":{"userAgent":"userAgent","requrl":"requrl","cid":"cid","img":"img","d":"d"}};var Xa=window.aax.err,Ya=window.aax.errConsts;Ya=Ya||{};Ya.get=Ya.get||{};Xa=Xa||{};var Za={},eb="",fb=encodeURIComponent(window.navigator.userAgent);eb=Xa.stack?Xa.stack:Xa.s?Xa.s:Xa.stacktrace?Xa.stacktrace:"No StackTrace";var gb="",hb;for(hb in Xa)Xa.hasOwnProperty&&Xa.hasOwnProperty(hb)&&(gb+=hb+" : '"+Xa[hb]+"',");Za.logLevel=3;Za.errorVal={};Za.errorVal.name=Ya.name;Za.errorVal.type=Ya.type;Za.errorVal.svr=Ya.svr;Za.errorVal.servname=Ya.servname;Za.errorVal.message=Ya.message;
Za.errorVal.stack=eb;Za.errorVal.objTrace=gb;var ib="";ib="object"===typeof JSON&&"undefined"!==typeof JSON.stringify?JSON.stringify(Za):Za.errorVal.name+"@#@"+Za.errorVal.type+"@#@"+eb+"@#@"+gb;ib=encodeURIComponent("["+ib+"]");var jb=Ya.hostName+Ya.path+"?"+Ya.get.userAgent+"="+fb+"&"+Ya.get.requrl+"="+encodeURIComponent(window.location.href)+"&"+Ya.get.cid+"="+Ya.customerId+"&"+Ya.get.C7+"=logo.gif&"+Ya.get.d+"="+ib;(new Image).src=jb;
};